services:
  trimitdown-web:
    build:
      context: ..
      dockerfile: docker-server/Dockerfile
    image: trimitdown-web:latest
    container_name: trimitdown-web
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - ./archive:/app/archive
      - ./certs:/certs:ro
